import { DEFAULT_UI_LANGUAGE, type UiLanguage } from '@/lib/ui-preferences';

const copy = {
	'zh-CN': {
		optionsTitle: 'Revornix Settings',
		optionsSubtitle: '管理网页翻译配置，并查看实时翻译日志。',
		settingsTab: '设置',
		logsTab: '日志',
		themeLabel: '主题',
		languageLabel: '语言',
		coreConfiguration: '核心配置',
		extensionSettings: '扩展设置',
		extensionSettingsDesc: '配置 Revornix 服务地址、网页翻译模型和悬浮按钮默认行为。',
		revornixApi: 'Revornix API',
		revornixApiDesc: '用于保存网页内容和调用你的主服务。',
		websiteTranslation: '网页翻译',
		websiteTranslationDesc: '配置 OpenAI 兼容模型服务，用于整页网页翻译。',
		baseUrl: 'Base Url',
		apiKey: 'Api Key',
		translationBaseUrl: '翻译服务 Base Url',
		translationApiKey: '翻译服务 Api Key',
		translationProvider: '翻译来源',
		translationProviderOpenAI: 'OpenAI 兼容模型',
		translationProviderGoogleFree: 'Google Translate 免费版',
		translationModel: '翻译模型',
		targetLanguage: '目标语言',
		defaultDisplayMode: '默认显示模式',
		translatedOnly: '仅译文',
		bilingual: '双语对照',
		floatingButton: '悬浮按钮',
		floatingButtonDesc: '在网页右侧显示悬浮翻译按钮，悬停可展开快捷配置。',
		save: '保存',
		saveSuccess: '保存成功',
		translationLogs: '翻译日志',
		translationLogsDesc: '查看翻译请求、批次进度、错误和页面内实时事件。',
		refresh: '刷新',
		refreshing: '刷新中...',
		clear: '清空',
		logsCleared: '日志已清空',
		searchLogs: '搜索日志',
		searchPlaceholder: '搜索 message 或 details',
		level: '级别',
		scope: '来源',
		allLevels: '全部级别',
		allScopes: '全部来源',
		logList: '日志列表',
		logCount: '共 {count} 条',
		noMatchedLogs: '暂无匹配日志',
		light: '浅色',
		dark: '深色',
		system: '跟随系统',
		widgetTitle: 'Revornix Translate',
		widgetSubtitle: 'Revornix网页悬浮翻译面板。',
		displayMode: '显示模式',
		autoTranslateSite: '当前站点自动翻译',
		autoTranslateSiteDesc: '打开页面后自动开始翻译',
		translateCurrentPage: '翻译当前页',
		translating: '翻译中',
		cancelTranslation: '中断翻译',
		cancellingTranslation: '中断中...',
		restoreOriginal: '恢复原文',
		openSettings: '打开详细设置',
		openLogs: '查看日志页面',
		openRevornixPanel: '打开 Revornix 面板',
		currentStateIdle: '当前状态：未翻译',
		translatingProgress: '翻译进度：{done}/{total} 节点',
		cancellingTranslationHint: '正在停止当前翻译任务...',
		translatedTo: '已翻译为 {language}',
		processedNodes: '共处理 {count} 个节点',
		batchesCompleted: '已完成 {done}/{total} 批',
		progressHint: '开始翻译后会实时显示进度',
		recentLogs: '最近 {count} 条',
		recentLogsEmpty: '开始翻译后会在这里实时显示过程日志',
		logsPageOpened: '已打开日志页面',
		selectionTranslateSuccess: '已翻译选中文本',
		selectionTranslateEmpty: '请先选中要翻译的文本',
		revornixPanelTitle: 'Revornix 工作台',
		revornixPanelSubtitle: '在网页右侧直接处理当前链接相关的 Revornix 操作。',
		revornixEditorTab: '文档创建/更新',
		revornixInfoTab: '文档信息',
		revornixCurrentPage: '当前页面',
		revornixRefreshPageData: '刷新',
		revornixPanelUrl: '当前链接',
		revornixPanelDocTitle: '文档标题',
		revornixPanelDocDescription: '文档描述',
		revornixLinkedDocument: '链接文档生成',
		revornixLinkedDocumentDesc: '把当前页面直接保存为 Revornix 网站文档。',
		revornixCreateLinkedDocument: '生成当前链接文档',
		revornixCreatingLinkedDocument: '生成中...',
		revornixLinkedDocumentCreated: '已创建当前链接文档',
		revornixCommentTitle: '追加评论',
		revornixCommentDesc: '为当前页面补充一条评论或笔记。',
		revornixCommentPlaceholder: '写点你的想法、补充说明或待办...',
		revornixSaveComment: '保存评论',
		revornixSavingComment: '保存中...',
		revornixCommentSaved: '评论已保存到 Revornix',
		revornixCommentEmpty: '请先输入评论内容',
		revornixNoteTitle: '追加笔记',
		revornixNoteDesc: '为当前文档补充一条关联笔记。',
		revornixNotePlaceholder: '写点阅读笔记、补充说明或待办...',
		revornixSaveNote: '保存笔记',
		revornixSavingNote: '保存中...',
		revornixNoteSaved: '笔记已追加到当前文档',
		revornixNoteEmpty: '请先输入笔记内容',
		revornixNoteDocumentRequired: '请先创建或选择当前页面对应文档，再追加笔记',
		revornixRecentNotes: '最近笔记',
		revornixPanelReady: '已连接到 Revornix，可直接执行操作。',
		revornixPanelConfigRequired: '请先在设置页填写 Revornix Base Url 和 Api Key。',
		revornixActionFailed: '操作失败，请稍后重试',
		revornixCommentDocumentPrefix: '评论：',
		revornixSourceLabel: '来源：',
		revornixLabels: '标签',
		revornixSections: '分区',
		revornixCreateLabel: '新建标签',
		revornixCreateSection: '新建分区',
		revornixLabelPlaceholder: '输入标签名',
		revornixSectionTitlePlaceholder: '分区标题',
		revornixSectionDescPlaceholder: '分区描述',
		revornixCreateLinkedDocumentUpdate: '更新已存在文档',
		revornixUpdatingLinkedDocument: '更新中...',
		revornixLinkedDocumentUpdated: '已更新当前链接文档',
		revornixExistingDocuments: '已有相关文档',
		revornixExistingDocumentsDesc: '优先复用当前链接对应的已有文档，避免重复创建。',
		revornixMatchedCurrentDocument: '已匹配当前链接文档',
		revornixNoMatchedDocuments: '暂未找到当前链接相关文档',
		revornixCreatingLabel: '创建标签中...',
		revornixCreatingSection: '创建分区中...',
		revornixCreatedLabel: '标签已创建',
		revornixCreatedSection: '分区已创建',
		revornixGraphTitle: '知识图谱',
		revornixGraphDesc: '查看当前文档的实体关系图谱，并在需要时触发构建。',
		revornixGraphGenerate: '生成知识图谱',
		revornixGraphRegenerate: '重新生成图谱',
		revornixGraphGenerating: '图谱构建中...',
		revornixGraphPending: '图谱任务已排队',
		revornixGraphBuilding: '知识图谱正在构建',
		revornixGraphFailed: '知识图谱构建失败',
		revornixGraphReady: '知识图谱已就绪',
		revornixGraphEmpty: '当前图谱暂无实体数据',
		revornixGraphNodes: '实体 {count}',
		revornixGraphEdges: '关系 {count}',
		revornixGraphTopEntities: '核心实体',
		revornixPodcastTitle: '音频播客',
		revornixPodcastDesc: '查看原始音频与 AI 播客结果，并支持触发播客生成。',
		revornixPodcastGenerate: '生成播客',
		revornixPodcastRegenerate: '重新生成播客',
		revornixPodcastGenerating: '播客生成中...',
		revornixPodcastPending: '播客任务已排队',
		revornixPodcastProcessing: 'AI 正在生成播客音频',
		revornixPodcastFailed: '播客生成失败',
		revornixPodcastReady: '播客已生成，可直接播放',
		revornixOriginalAudio: '原始音频',
		revornixPodcastAudio: '播客音频',
		revornixNoAudio: '当前文档暂无原始音频',
		revornixNoPodcast: '当前文档还没有播客结果',
	},
	en: {
		optionsTitle: 'Revornix Settings',
		optionsSubtitle: 'Manage translation settings and review live translation logs.',
		settingsTab: 'Settings',
		logsTab: 'Logs',
		themeLabel: 'Theme',
		languageLabel: 'Language',
		coreConfiguration: 'Core Configuration',
		extensionSettings: 'Extension Settings',
		extensionSettingsDesc: 'Configure Revornix endpoints, translation model, and floating widget defaults.',
		revornixApi: 'Revornix API',
		revornixApiDesc: 'Used to save content and call your primary Revornix service.',
		websiteTranslation: 'Website Translation',
		websiteTranslationDesc: 'Configure an OpenAI-compatible service for full-page translation.',
		baseUrl: 'Base Url',
		apiKey: 'Api Key',
		translationBaseUrl: 'Translation Base Url',
		translationApiKey: 'Translation Api Key',
		translationProvider: 'Translation Provider',
		translationProviderOpenAI: 'OpenAI Compatible',
		translationProviderGoogleFree: 'Google Translate (Free)',
		translationModel: 'Translation Model',
		targetLanguage: 'Target Language',
		defaultDisplayMode: 'Default Display Mode',
		translatedOnly: 'Translated Only',
		bilingual: 'Bilingual',
		floatingButton: 'Floating Button',
		floatingButtonDesc: 'Show a floating translation button on webpages and expand quick controls on hover.',
		save: 'Save',
		saveSuccess: 'Saved successfully',
		translationLogs: 'Translation Logs',
		translationLogsDesc: 'Review requests, chunk progress, errors, and live page events.',
		refresh: 'Refresh',
		refreshing: 'Refreshing...',
		clear: 'Clear',
		logsCleared: 'Logs cleared',
		searchLogs: 'Search Logs',
		searchPlaceholder: 'Search message or details',
		level: 'Level',
		scope: 'Scope',
		allLevels: 'All Levels',
		allScopes: 'All Scopes',
		logList: 'Log List',
		logCount: '{count} entries',
		noMatchedLogs: 'No matching logs',
		light: 'Light',
		dark: 'Dark',
		system: 'System',
		widgetTitle: 'Revornix Translate',
		widgetSubtitle: 'A React + shadcn powered floating translation panel for webpages.',
		displayMode: 'Display Mode',
		autoTranslateSite: 'Auto-translate This Site',
		autoTranslateSiteDesc: 'Start translating automatically when the page opens.',
		translateCurrentPage: 'Translate Page',
		translating: 'Translating',
		cancelTranslation: 'Cancel Translation',
		cancellingTranslation: 'Cancelling...',
		restoreOriginal: 'Restore Original',
		openSettings: 'Open Settings',
		openLogs: 'Open Logs Page',
		openRevornixPanel: 'Open Revornix Panel',
		currentStateIdle: 'Current state: idle',
		translatingProgress: 'Progress: {done}/{total} nodes',
		cancellingTranslationHint: 'Stopping the current translation task...',
		translatedTo: 'Translated to {language}',
		processedNodes: '{count} nodes processed',
		batchesCompleted: '{done}/{total} batches completed',
		progressHint: 'Progress will appear here during translation',
		recentLogs: 'Recent {count}',
		recentLogsEmpty: 'Recent translation logs will appear here',
		logsPageOpened: 'Logs page opened',
		selectionTranslateSuccess: 'Selected text translated',
		selectionTranslateEmpty: 'Select some text first',
		revornixPanelTitle: 'Revornix Workspace',
		revornixPanelSubtitle: 'Handle current-page Revornix actions directly from the webpage.',
		revornixEditorTab: 'Create / Update',
		revornixInfoTab: 'Document Info',
		revornixCurrentPage: 'Current Page',
		revornixRefreshPageData: 'Refresh',
		revornixPanelUrl: 'Current Url',
		revornixPanelDocTitle: 'Document Title',
		revornixPanelDocDescription: 'Document Description',
		revornixLinkedDocument: 'Linked Document',
		revornixLinkedDocumentDesc: 'Save the current page directly as a Revornix website document.',
		revornixCreateLinkedDocument: 'Create Linked Document',
		revornixCreatingLinkedDocument: 'Creating...',
		revornixLinkedDocumentCreated: 'Linked document created',
		revornixCommentTitle: 'Append Comment',
		revornixCommentDesc: 'Add a comment or note for the current page.',
		revornixCommentPlaceholder: 'Write your thoughts, notes, or next steps...',
		revornixSaveComment: 'Save Comment',
		revornixSavingComment: 'Saving...',
		revornixCommentSaved: 'Comment saved to Revornix',
		revornixCommentEmpty: 'Please enter a comment first',
		revornixNoteTitle: 'Append Note',
		revornixNoteDesc: 'Add a note tied to the current document.',
		revornixNotePlaceholder: 'Write your reading notes, context, or follow-up tasks...',
		revornixSaveNote: 'Save Note',
		revornixSavingNote: 'Saving...',
		revornixNoteSaved: 'Note added to the current document',
		revornixNoteEmpty: 'Please enter a note first',
		revornixNoteDocumentRequired: 'Create or select the current-page document before adding notes',
		revornixRecentNotes: 'Recent Notes',
		revornixPanelReady: 'Connected to Revornix and ready.',
		revornixPanelConfigRequired: 'Please configure Revornix Base Url and Api Key in settings first.',
		revornixActionFailed: 'Action failed. Please try again.',
		revornixCommentDocumentPrefix: 'Comment: ',
		revornixSourceLabel: 'Source: ',
		revornixLabels: 'Labels',
		revornixSections: 'Sections',
		revornixCreateLabel: 'Create Label',
		revornixCreateSection: 'Create Section',
		revornixLabelPlaceholder: 'Enter label name',
		revornixSectionTitlePlaceholder: 'Section title',
		revornixSectionDescPlaceholder: 'Section description',
		revornixCreateLinkedDocumentUpdate: 'Update Existing Document',
		revornixUpdatingLinkedDocument: 'Updating...',
		revornixLinkedDocumentUpdated: 'Linked document updated',
		revornixExistingDocuments: 'Matched Documents',
		revornixExistingDocumentsDesc: 'Reuse the current-page document when possible to avoid duplicates.',
		revornixMatchedCurrentDocument: 'Matched current page document',
		revornixNoMatchedDocuments: 'No related document found yet',
		revornixCreatingLabel: 'Creating label...',
		revornixCreatingSection: 'Creating section...',
		revornixCreatedLabel: 'Label created',
		revornixCreatedSection: 'Section created',
		revornixGraphTitle: 'Knowledge Graph',
		revornixGraphDesc: 'Inspect the current document graph and trigger generation when needed.',
		revornixGraphGenerate: 'Generate Graph',
		revornixGraphRegenerate: 'Regenerate Graph',
		revornixGraphGenerating: 'Building graph...',
		revornixGraphPending: 'Graph task queued',
		revornixGraphBuilding: 'Knowledge graph is building',
		revornixGraphFailed: 'Knowledge graph generation failed',
		revornixGraphReady: 'Knowledge graph is ready',
		revornixGraphEmpty: 'No graph entities available yet',
		revornixGraphNodes: '{count} nodes',
		revornixGraphEdges: '{count} edges',
		revornixGraphTopEntities: 'Top entities',
		revornixPodcastTitle: 'Audio & Podcast',
		revornixPodcastDesc: 'Review source audio and generated podcast output, then regenerate when needed.',
		revornixPodcastGenerate: 'Generate Podcast',
		revornixPodcastRegenerate: 'Regenerate Podcast',
		revornixPodcastGenerating: 'Generating podcast...',
		revornixPodcastPending: 'Podcast task queued',
		revornixPodcastProcessing: 'AI is generating podcast audio',
		revornixPodcastFailed: 'Podcast generation failed',
		revornixPodcastReady: 'Podcast is ready to play',
		revornixOriginalAudio: 'Original Audio',
		revornixPodcastAudio: 'Podcast Audio',
		revornixNoAudio: 'This document has no source audio',
		revornixNoPodcast: 'No podcast result for this document yet',
	},
} as const;

export function getUiCopy(language: UiLanguage = DEFAULT_UI_LANGUAGE) {
	return copy[language] || copy[DEFAULT_UI_LANGUAGE];
}

export function formatCopy(template: string, values: Record<string, string | number>) {
	return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? ''));
}
